config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'


  root 'welcome#index'
  resources :about, only: [:index]

  get 'password', to: "passwords#edit", as: :edit_password
  patch 'password', to: "passwords#update"

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # sends out email
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  # performs reset itself
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'auth/twitter/callback', to: "omniauth_callbacks#twitter"

  get '/progress_bar', to: "automated_tweets#progress_bar"
  resources :twitter_accounts
  resources :tweets

  resources :automated_tweets
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user.present?
			PasswordMailer.with(user: @user).reset.deliver_now
		end
		redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password."
	end

	def edit
		@user = User.find_signed!(params[:token], purpose: "password_reset")
	rescue ActiveSupport::MessageVerifier::InvalidSignature
		redirect_to sign_in_path, alert: "Your token has expired please try again."
	end

	def update
		@user = User.find_signed!(params[:token], purpose: "password_reset")
		if @user.update(password_params)
			redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
		else
			render :edit
		end
	end

	private

	def password_params
		params.require(:user).permit(:password, :password_confirmation)
	end

end

app/views/password_resets/edit.html.erb
<div class="my-2 pb-5">
  <h3 class="mt-3 text-4xl leading-8 font-medium tracking-tight text-gray-900">Reset your password</h3>
</div>


<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), local: true do |f| %>

  <%= render partial: "shared/form_errors", locals: {f: f} %>

  <div class="mb-3">
    <%= f.password_field :password, class: "input", placeholder: "password" %>
  </div>

  <div class="mb-3">
    <%= f.password_field :password_confirmation, class: "input", placeholder: "password confirmation" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Reset Password", class: "btn-blue" %>
  </div>

<% end %>

app/views/password_resets/new.html.erb
<div class="my-2 pb-5">
  <h3 class="mt-3 text-4xl leading-8 font-medium tracking-tight text-gray-900">Forgot your password?</h3>
</div>


<%= form_with url: password_reset_path do |f| %>

  <div class="mb-3">
    <%= f.text_field :email, class: "input", placeholder: "example@email.com" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Reset Password", class: "btn-blue" %>
  </div>

<% end %>