config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'


  root 'welcome#index'
  resources :about, only: [:index]

  get 'password', to: "passwords#edit", as: :edit_password
  patch 'password', to: "passwords#update"

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # sends out email
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  # performs reset itself
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'auth/twitter/callback', to: "omniauth_callbacks#twitter"

  get '/progress_bar', to: "automated_tweets#progress_bar"
  resources :twitter_accounts
  resources :tweets

  resources :automated_tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  after_save do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :require_user_logged_in!
	before_action :set_tweet, only: [:edit, :update, :destroy]

	def index
		@tweets = Current.user.tweets
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Current.user.tweets.create(tweet_params)
		if @tweet.save
			redirect_to tweets_path, notice: "Tweet was scheduled successfully"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @tweet.update(tweet_params)
			redirect_to tweets_path, notice: "Tweet was updated successfully"
		else
			render :edit
		end
	end

	def destroy
		@tweet.destroy
		redirect_to tweets_path, notice: "Tweet was unscheduled successfully"
	end

	private

	def tweet_params
		params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
	end

	def set_tweet
		@tweet = Current.user.tweets.find(params[:id])
	end

end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |f| %>

  <%= render partial: "shared/form_errors", locals: {f: f} %>

  <div class="mb-3">
    <%= f.label :twitter_account_id %>
    <%= f.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "input"} %>
  </div>

  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, class: "input" %>
  </div>

  <div class="mb-6">
    <%= f.label :publish_at %>
    <%= f.text_field :publish_at,
                     data: {
                       controller: "flatpickr",
                       flatpickr_enable_time: true,
                       flatpickr_alt_format: "F j, Y" + " at " + "h:i K",
                       flatpickr_alt_input: true,
                       disable_mobile: true,
                       flatpickr_min_date: Time.zone.now
                     } %>
  </div>

  <div class="actions">
    <%= f.button "Schedule", class: "btn-blue" %>

    <% if f.object.persisted? %>
      <%= link_to "Delete", f.object, method: :delete, data: { confirm: "Are you sure?" }, class: "btn-red" %>
    <% end %>
  </div>

<% end %>

app/views/tweets/_tweet.html.erb
<%= render(TweetComponent.new(tweet: tweet)) %>

app/views/tweets/edit.html.erb
<div class="my-2 pb-5">
  <h3 class="mt-3 text-4xl leading-8 font-medium tracking-tight text-gray-900">Edit Scheduled Tweet</h3>
</div>


<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="flex justify-between min-w-max">
  <div class="my-2">
    <h3 class="mt-3 text-4xl leading-8 font-medium tracking-tight text-gray-900">Scheduled Tweets</h3>
  </div>
  <div class="my-6">
    <% if Current.user.twitter_accounts.any? %>
      <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn-blue" %>
    <% end %>

    <% if Current.user.twitter_accounts.none? %>
      <%= link_to "Add a Twitter account", '/auth/twitter', method: :post, class: "btn-blue"  %>
    <% end %>
  </div>
</div>
<br>
<br>

<%= render @tweets %>

app/views/tweets/new.html.erb
<div class="my-2 pb-5">
  <h3 class="mt-3 text-4xl leading-8 font-medium tracking-tight text-gray-900">Schedule A Tweet</h3>
</div>

<%= render "form", tweet: @tweet %>