config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'


  root 'welcome#index'
  resources :about, only: [:index]

  get 'password', to: "passwords#edit", as: :edit_password
  patch 'password', to: "passwords#update"

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # sends out email
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  # performs reset itself
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'auth/twitter/callback', to: "omniauth_callbacks#twitter"

  get '/progress_bar', to: "automated_tweets#progress_bar"
  resources :twitter_accounts
  resources :tweets

  resources :automated_tweets
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
    <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded-full px-4 py-3 rounded-full relative bg-green-400 text-white pointer-events-auto">
      <div class="p-2">
        <div class="flex items-start">
          <p class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm leading-5 font-medium"><%= flash[:notice] %></p>
          <div class="ml-4 flex-shrink-0 flex">
            <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
    <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded-full px-4 py-3 rounded-full relative bg-green-400 text-white pointer-events-auto">
      <div class="p-2">
        <div class="flex items-start">
          <p class="ml-3 w-0 flex-1 pt-0.5">
          <p class="text-sm leading-5 font-medium"><%= flash[:alert] %></p>
          <div class="ml-4 flex-shrink-0 flex">
            <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if f.object.errors.any? %>
  <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
    <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded-full px-4 py-3 rounded-full relative bg-red-400 text-white pointer-events-auto">
      <div class="p-2">
        <div class="flex items-start">
          <p class="ml-3 w-0 flex-1 pt-0.5">
            <% f.object.errors.full_messages.each do |error| %>
              <p class="text-sm leading-5 font-medium"><%= error %></p>
            <% end %>
          <div class="ml-4 flex-shrink-0 flex">
            <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="w-64 flex-shrink-0">
  <div class="flex-auto bg-gray-900 h-full">
    <div class="flex flex-col overflow-y-auto">
      <ul class="relative m-0 p-0 list-none h-full">
        <li class="text-white text-xl p-5 w-full flex relative shadow-sm justify-start bg-gray-800 border-b-2 border-gray-700">
          <%= image_tag "favicon.png", size: "30x30" %>
          <%= link_to "Tweet-O-Matic", root_path, class: "hover:text-blue-400 pl-2" %>
        </li>
        <li>
        </li>
        <% if Current.user %>
        <li class="p-4 w-full flex relative shadow-sm">
          <div class="flex-auto my-1">
            <span class="text-white font-medium"><%= "Welcome #{Current.user.email.capitalize}!" %></span>
          </div>
        </li>
        <% else %>
        <li class="p-4 w-full flex relative shadow-sm">
          <div class="flex-auto my-1">
            <span class="text-white font-medium"><%= "Welcome!" %></span>
          </div>
        </li>
        <% end %>

        <% if Current.user %>
        <div class="text-gray-400 flex relative px-4 hover:bg-gray-700 cursor-pointer">
          <div class="mr-4 my-auto">
            <svg class="fill-current h-5 w-5" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z"></path></svg>
          </div>
          <div class="flex-auto my-1">
            <%= link_to "Twitter Accounts", twitter_accounts_path, class: "#{current? "active-link", twitter_accounts_path}"  %>
          </div>
        </div>

        <div class="text-gray-400 flex relative px-4 hover:bg-gray-700 cursor-pointer">
          <div class="mr-4 my-auto">
            <svg class="fill-current h-5 w-5" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 13H5c-1.1 0-2 .9-2 2v4c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-4c0-1.1-.9-2-2-2zM7 19c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zM19 3H5c-1.1 0-2 .9-2 2v4c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM7 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"></path></svg>
          </div>
          <div class="flex-auto my-1">
            <%= link_to "Scheduled Tweets", tweets_path, class: "#{current? "active-link", tweets_path}"  %>
          </div>
        </div>

        <div class="text-gray-400 flex relative px-4 hover:bg-gray-700 cursor-pointer">
          <div class="mr-4 my-auto">
            <svg class="fill-current h-5 w-5" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M21 3H3C2 3 1 4 1 5v14c0 1.1.9 2 2 2h18c1 0 2-1 2-2V5c0-1-1-2-2-2zM5 17l3.5-4.5 2.5 3.01L14.5 11l4.5 6H5z"></path></svg>            </div>
          <div class="flex-auto my-1">
            <%= link_to "Automation", automated_tweets_path, method: :get, class: "#{current? "active-link", automated_tweets_path}" %>
          </div>
        </div>
        <% end %>

        <div class="text-gray-400 flex relative px-4 hover:bg-gray-700 cursor-pointer">
          <div class="mr-4 my-auto">
            <svg class="fill-current h-5 w-5" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"></path></svg>            </div>
          <div class="flex-auto my-1">
            <%= link_to "About", about_index_path, class: "#{current? "active-link", about_index_path}"  %>
          </div>
        </div>
      </ul>
    </div>
  </div>
</nav>

<!--<div class="flex flex-col w-full">-->
<!--  <header class="text-white bg-blue-400 sticky left-auto top-0 right-0 p-3">-->
<!--    <div class="h-12 px-6 flex relative items-center justify-end">-->
<!--      <button class="flex mx-4 text-white hover:text-gray-200 focus:outline-none">-->
<!--        <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">-->
<!--          <path d="M15 17H20L18.5951 15.5951C18.2141 15.2141 18 14.6973 18 14.1585V11C18 8.38757 16.3304 6.16509 14 5.34142V5C14 3.89543 13.1046 3 12 3C10.8954 3 10 3.89543 10 5V5.34142C7.66962 6.16509 6 8.38757 6 11V14.1585C6 14.6973 5.78595 15.2141 5.40493 15.5951L4 17H9M15 17V18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18V17M15 17H9" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">-->
<!--          </path>-->
<!--        </svg>-->
<!--      </button>-->

<!--      <button class="relative block h-8 w-8 rounded-full overflow-hidden shadow focus:outline-none">-->
<!--          <img class="h-full w-full object-cover" src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar">-->
        <%#= image_tag "favicon.png", size: "30x30", class: "h-full w-full object-cover"%>
<!--      </button>-->
<!--    </div>-->
<!--  </header>-->
<!--</div>-->
<!--    <div class="text-white bg-blue-400 flex w-full">-->
<!--      <div class="flex overflow-hidden h-12 ml-2">-->
<!--        <button class="mx-3 border-b-2 border-white">-->
<!--          <span>Users</span>-->
<!--        </button>-->

<!--        <button class="mx-3 hover:border-b-2 border-white">-->
<!--          <span>Sign-in method</span>-->
<!--        </button>-->

<!--        <button class="mx-3 hover:border-b-2 border-white">-->
<!--          <span>Templates</span>-->
<!--        </button>-->

<!--        <button class="mx-3 hover:border-b-2 border-white">-->
<!--          <span>Usage</span>-->
<!--        </button>-->
<!--      </div>-->
<!--    </div>-->
<!--</div>-->

app/views/shared/_topbar.html.erb
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<header class="bg-blue-400 p-3">
  <div class="h-12 px-6 flex items-center justify-end">
    <div class="relative" data-controller="dropdown">
      <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="inline-block select-none">
        <nav x-data="{ open: false }">
          <button class="text-white-500 w-10 h-10 relative focus:outline-none bg-blue-400" @click="open = !open">
            <div class="block w-5 absolute left-1/2 top-1/2   transform  -translate-x-1/2 -translate-y-1/2">
              <span aria-hidden="true" class="block absolute h-0.5 w-8 bg-white transform transition duration-500 ease-in-out" :class="{'rotate-45': open,' -translate-y-1.5': !open }"></span>
              <span aria-hidden="true" class="block absolute  h-0.5 w-8 bg-white   transform transition duration-500 ease-in-out" :class="{'opacity-0': open } "></span>
              <span aria-hidden="true" class="block absolute  h-0.5 w-8 bg-white transform  transition duration-500 ease-in-out" :class="{'-rotate-45': open, ' translate-y-1.5': !open}"></span>
            </div>
          </button>
        </nav>
      </div>
      <div data-dropdown-target="menu" class="absolute right-0 mt-2 hidden">
        <div class="bg-white shadow rounded border overflow-hidden">
          <% if Current.user %>
            <%= link_to "Account", edit_password_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 text-gray-900 bg-white hover:bg-blue-400 whitespace-no-wrap' %>
            <%= link_to "Logout", logout_path, method: :delete, data: {action: "click->dropdown#toggle"}, class: 'no-underline block pl-8 py-3 text-gray-900 bg-white hover:bg-blue-400 whitespace-no-wrap' %>
          <% else %>
            <%= link_to "Register", sign_up_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 text-gray-900 bg-white hover:bg-blue-400 whitespace-no-wrap' %>
            <%= link_to "Sign In", sign_in_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block pl-8 py-3 text-gray-900 bg-white hover:bg-blue-400 whitespace-no-wrap' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/old_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= image_tag "favicon.png", size: "30x30" %>
    <%= link_to "Tweet-O-Matic", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Automation", automated_tweets_path, method: :get, class: "nav-link", id: "automation-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_index_path, class: "nav-link"  %>
        </li>
      </ul>

      <ul class="nav navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</nav>